{
 "title": "Jaeger",
 "time": { "from": "now-4h", "to": "now" },
 "panels": [
  {
   "title": "Ai api 5m 请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jaeger_operations_duration_5m_requests{exported_service=~\".*ai_api\"}) by (operationname)"
    }
   ]
  },
  {
   "title": "Ai Power 5m 请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jaeger_operations_duration_5m_requests{exported_service=~\".*ai_power\"}) by (operationname)"
    }
   ]
  },
  {
   "title": "Ai-Manage 5m 请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jaeger_operations_duration_5m_requests{exported_service=~\".*ai_manage\"}) by (operationname)"
    }
   ]
  },
  {
   "title": "Eagel 5m 请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jaeger_operations_duration_5m_requests{exported_service=\"eagle\"}) by (operationname)"
    }
   ]
  }
 ]
}